### ISSUE TITLE
无法更改模式/部分指令无法运行

### ISSUE THREAD

**Issue by DyingJKJ** [fbef0102/Rotoblin-AZMod#10]
L 12/16/2023 - 14:49:39: SourceMod error session started
L 12/16/2023 - 14:49:39: Info (map "l4d_vs_airport01_greenhouse") (file "/home/steam/l4d1/left4dead/addons/sourcemod/logs/errors_20231216.log")
L 12/16/2023 - 14:49:39: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:49:42: [SM] Exception reported: Plugin owning this native is currently paused.
L 12/16/2023 - 14:49:42: [SM] Blaming: l4d_versus_same_UnprohibitBosses.smx
L 12/16/2023 - 14:49:42: [SM] Call stack trace:
L 12/16/2023 - 14:49:42: [SM]   [0] GetSurCurrentFloat
L 12/16/2023 - 14:49:42: [SM]   [1] Line 222, l4d_versus_same_UnprohibitBosses.sp::COLD_DOWN
L 12/16/2023 - 14:49:48: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:49:48: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:49:49: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:49:49: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:50:01: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:50:01: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:50:09: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:50:51: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
L 12/16/2023 - 14:50:53: [savechat.smx] Can not create chat file: addons/sourcemod//logs/chat/server_27015_chat_23_12_16.log
[errors_20231216.log](https://github.com/fbef0102/Rotoblin-AZMod/files/13691661/errors_20231216.log)
[L20231216.log](https://github.com/fbef0102/Rotoblin-AZMod/files/13691662/L20231216.log)
PS metamod无报错日志

**Comment by DyingJKJ** [comment]
sourcemod，metamod，rotoaz都重装过

**Comment by fbef0102** [comment]
linux系統創造文件的權限不足
請自行在addons/sourcemod/logs 創造chat資料夾並給予 讀/寫/執行 的權限
```c
chmod -R 777 chat/
```

**Comment by DyingJKJ** [comment]
> linux系統創造文件的權限不足 請自行在addons/sourcemod/logs 創造chat資料夾並給予 讀/寫/執行 的權限
> 
> ```c
> chmod -R 777 chat/
> ```

已解决
