### ISSUE TITLE
老哥，这东西太好了。

### ISSUE THREAD

**Issue by ivanlee93** [fbef0102/Rotoblin-AZMod#2]
有没有L4D2的版本，求分享。隔壁SirPlease的ZoneMod还有Apex都是只有英文的

**Comment by fbef0102** [comment]
現階段這個專案“Roto-AZ”沒有L4D2版本
此專案大部分遊戲插件本來就是從二代移植過來
因此只適用於一代
(Github只公開英文版本，中文版本在我手上)

二代已經有很多大佬在完善對抗
Zonemod, Nextmod, openmod
不缺我一個過去

有興趣可查看我的其他專案
[適用二代插件](https://github.com/fbef0102/L4D2-Plugins)
[適用一代對抗競技插件](https://github.com/fbef0102/L4D1-Competitive-Plugins)
[通用一二代插件](https://github.com/fbef0102/L4D1_2-Plugins)
