### ISSUE TITLE
Witch spawning during ready up

### ISSUE THREAD

**Issue by Icy-Inferno** [fbef0102/Rotoblin-AZMod#3]
Hi, I'm sorry if this is the wrong repository to submit this issue to. The tank waits to spawn until ready up is over and the survivors leave the safe area, but the witch does not. With an early enough witch boss flow %, the witch will spawn during ready up. This is a big problem if survivors manage to attack her before ready up is finished. Thank you for your hard work!

**Comment by fbef0102** [comment]
Thanks report, I fixed and updated, check v8.2.4 updated (2020_10_16)
