### ISSUE TITLE
Vote kick 

### ISSUE THREAD

**Issue by Arnim0** [fbef0102/Rotoblin-AZMod#4]
Vote kick not working at all. all says immune makes it harder for players that want to kick noobs

**Comment by fbef0102** [comment]
Fixed, updated version
* The player would be banned for 10 mins if get vote-kicked. (Ban is still working even if player leaves server during vote)

**Comment by Arnim0** [comment]
The problem is they can’t only has to be kicked by admin all others can’t how to fix that in sp file need to recompile it ?

**Comment by fbef0102** [comment]
If you are admin, use !admin -> Player Commands -> Kick Player
If you are non-admin, use !votes -> Kick Player to kick player who doesn't have immune access

To update the plugin, simply download [votes3.smx](https://github.com/fbef0102/Rotoblin-AZMod/blob/master/left4dead/addons/sourcemod/plugins/votes3.smx) file-> override -> restart server.

To change immune access or pass percentage,
write down cvar in cfg\Reloadables\server_custom_convars.cfg
```
\\Players with these flags have kick immune. (Empty = Everyone, -1: Nobody)
l4d_vote_Kick_immue_access_flag "z"

\\Pass vote percentage.
sm_votes_s "0.60"
```

**Comment by Arnim0** [comment]
I am admin and my friend did tell me that can’t kick even none admins  
Will update it and see if there is still bugs
