### ISSUE TITLE
Hunter cvar 

### ISSUE THREAD

**Issue by Arnim0** [fbef0102/Rotoblin-AZMod#7]
Hello again :) I have **question** about what cvar will  stop or disable deadstop   To add to server cfg  
Thanks again

**Comment by fbef0102** [comment]
```
//versus hunter shove when stand still or duck
sm_cvar versus_shove_hunter_fov	"50"

//versus hunter shove when pouncing
sm_cvar versus_shove_hunter_fov_pouncing "0"
```

better write down your own cvar settings in **cfg/Reloadables/server_custom_convars.cfg**

**Comment by Arnim0** [comment]
Thanks brother yes very helpful cfg without messing others

**Comment by Arnim0** [comment]
I have another question 
What is cvar for max ammo  like **smg**, **pump-shotgun**  if I want to increase ammo size ?

Also to to turn off chat and voice to  **spectators**
When I type **sm_hear** nothing happened  
Thanks again 🙂

**Comment by Arnim0** [comment]
I deleted comment by mistake 
How to turn off chat to  spectators can’t see **infected or survivor** only if chat to all can see and they can’t hear both side  when I type sm_hear seems do nothing 


thanks 🙏 again

**Comment by fbef0102** [comment]
Fixed. 
Update [l4d_versus_specListener.smx](https://github.com/fbef0102/Rotoblin-AZMod/blob/master/left4dead/addons/sourcemod/plugins/l4d_versus_specListener.smx)

**Comment by Arnim0** [comment]
Thanks man 
I found few bugs will list them all at ones
