### ISSUE TITLE
Sv bugs

### ISSUE THREAD

**Issue by Arnim0** [fbef0102/Rotoblin-AZMod#8]
L4d Bugs
 1- **1v1 hunters** won’t spawn  tank even I tried to enable tank control  still won’t spawn and at the end keep slaying tank, and also spawn pills  not sure if plugins or cfg 

2- **Witch**  bugs if I step on witch to crown her will **instantly slay who ever step on witch** if from map drops like truck or edge and fall on her will be dead I tested it many times keep doing it

3-**rcon** **console**  when I wipe server and set password works just fine like when I say ,say “hello” when I install server package   Won’t show anything I get this msg 
**No response from the server (this may be an invalid command)** but when I restart it and type it works then stop 

I had to report it to you man if can be fixed or won't be fixed

**Comment by fbef0102** [comment]
1. **1v1 hunters**
It is not bug, I do it on purpose, no tank and witch in 1v1. Just practice to skeet hunter.
In multi hunters mode, spawn pills on the map, I do it on purpose, too.

2. **Witch bugs**
It is source engine bug, I will try to fix it.

3. **rcon console**
I don't understand what you talking about, can you please explain more clearly?

**Comment by Arnim0** [comment]
1- Ok that make sense because players used to play 1v1 hunters spawn tank it loads !load 1V1 hunters only cfg And there is 1v2 that seemed to me just practice but 1v1 seemed to me not even friend yesterday said that to 


-3 it's rcon tools to where to manage server restart or stop server it works fine just something blocking that command from using it if I want to talk someone from it ask how is server without be in game I added attachment  but if you still don't understand don't worry about it not big deal 🙂
![image](https://user-images.githubusercontent.com/111248753/186894410-c898eaf1-8762-498c-9f0c-7dd55f8ce2a6.jpeg)


3-witch bug for sure is 
Over all thanks again for work you do 🙏

**Comment by fbef0102** [comment]
try this one, fix witch instant kill bug
[l4d2_block_rocketjump.zip](https://github.com/fbef0102/Rotoblin-AZMod/files/9433807/l4d2_block_rocketjump.zip)

**Comment by Arnim0** [comment]
I will test it and update you thanks

**Comment by Arnim0** [comment]
I tried it seems not fixed sound like I jumped off building and instantly death

**Comment by fbef0102** [comment]
> I tried it seems not fixed sound like I jumped off building and instantly death
[l4d2_block_rocketjump.zip](https://github.com/fbef0102/Rotoblin-AZMod/files/9436992/l4d2_block_rocketjump.zip)

**Comment by Arnim0** [comment]
I tried  more than 4 times seems it’s working now fine I did not see any issues so far now witch feels like witch not high building  lol to jump off from  thanks again 🙏

**Comment by Arnim0** [comment]
Hey man what is that command do 
**rotoblin_enable_2v2** If set 1 will slay bot if I become tank  like   if I pounce **Survivor** before I get **tank** **hunter** will stay alive until cleared or should be ****slayed**!** is this how suppose to work or it’s bugs that command won’t do anything if I set it to 1 or 0 ?

**Comment by fbef0102** [comment]
> // slay AI Hunter, AI Smoker and slay AI Tank if human tank player lose controls
> rotoblin_enable_2v2 1

**Comment by Arnim0** [comment]
Oh had no idea thanks for that  so if I do **2v2 hunters** me and my buddy attack before tank spawn  this will automatically slay my ai hunter or will stay alive until cleared  my friends told me to check that and I did see it was set 1  but never slayed my ai hunter game ended when I became tank
