### ISSUE TITLE
Wrong name of the plugin

### ISSUE THREAD

**Issue by MrGosling** [fbef0102/Rotoblin-AZMod#9]
Hi! l4d_vesus_nerf_huntingrifle.smx. It should be l4d_versus_nerf_huntingrifle.smx, I suppose)

**Comment by fbef0102** [comment]
Thank you, will rename in next version

**Comment by fbef0102** [comment]
Rename **l4d_versus_nerf_huntingrifle.smx** in v8.5.2, thanks for report
